"""scripts/ego4d_score_expand.py — score additional Ego4D candidate windows
generated by raising --per-file-cap (50 -> 150) for the 946 already-safe
TRAIN files only (never the 350 frozen held-out files), to recover real
headroom the original 50-window/file cap left unscored. Reuses the exact
same scoring formula as scripts/ego4d_av_relevance_filter.py (imports
extract_audio/energy_cov/SPEECH_IDX/NOISE_LIKE_IDX directly, same pattern
as scripts/ego4d_score_backfill.py).

Input candidates file (list of {source_id, path, start_sec}) must already
exclude anything in the existing incremental score cache (net-new only).

Usage (per-GPU shard):
    CUDA_VISIBLE_DEVICES=0 python scripts/ego4d_score_expand.py --shard-idx 0 --num-shards 4
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time

import numpy as np
import torch

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from scripts.ego4d_av_relevance_filter import extract_audio, energy_cov, SPEECH_IDX, NOISE_LIKE_IDX, AUDIO_SR

CANDIDATES_PATH = "/tmp/ego4d_new_candidates_cap150.json"
OUT_DIR = "checkpoints/vjepa21_shelved"


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--shard-idx", type=int, default=0)
    p.add_argument("--num-shards", type=int, default=1)
    p.add_argument("--candidates", default=CANDIDATES_PATH)
    args = p.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[ego4d-expand] shard {args.shard_idx}/{args.num_shards} device={device}", flush=True)

    candidates = json.load(open(args.candidates))
    my_candidates = [c for i, c in enumerate(candidates) if i % args.num_shards == args.shard_idx]
    print(f"[ego4d-expand] shard {args.shard_idx}: {len(my_candidates)}/{len(candidates)} candidates", flush=True)

    vad_model, vad_utils = torch.hub.load(repo_or_dir="snakers4/silero-vad", model="silero_vad", trust_repo=True)
    get_speech_timestamps = vad_utils[0]

    from transformers import AutoFeatureExtractor, AutoModelForAudioClassification
    ast_name = "MIT/ast-finetuned-audioset-10-10-0.4593"
    ast_fe = AutoFeatureExtractor.from_pretrained(ast_name)
    ast_model = AutoModelForAudioClassification.from_pretrained(ast_name).to(device).eval()
    id2label = ast_model.config.id2label

    out_path = os.path.join(OUT_DIR, f"ego4d_expand_scores_shard{args.shard_idx}.json")
    scored = []
    if os.path.isfile(out_path):
        scored = json.load(open(out_path))
        print(f"[ego4d-expand] shard {args.shard_idx}: RESUMING {len(scored)} already scored", flush=True)

    t_start = time.time()
    for i, c in enumerate(my_candidates):
        if i < len(scored):
            continue
        try:
            audio = extract_audio(c["path"], c["start_sec"])
            wav_t = torch.from_numpy(audio)
            speech_ts = get_speech_timestamps(wav_t, vad_model, sampling_rate=AUDIO_SR)
            speech_samples = sum(t["end"] - t["start"] for t in speech_ts)
            vad_speech_frac = speech_samples / audio.shape[0]

            inputs = ast_fe(audio, sampling_rate=AUDIO_SR, return_tensors="pt")
            with torch.no_grad():
                logits = ast_model(**{k: v.to(device) for k, v in inputs.items()}).logits
                probs = torch.softmax(logits, dim=-1)[0].cpu().numpy()
            mask = np.ones(probs.shape[0], dtype=bool)
            mask[SPEECH_IDX] = False
            mask[NOISE_LIKE_IDX] = False
            top_event_idx = int(np.argmax(probs * mask))
            top_event_prob = float(probs[top_event_idx])
            speech_prob = float(probs[SPEECH_IDX].sum())

            cov = energy_cov(audio)
            cov_norm = min(1.0, cov / 2.0)

            score = top_event_prob * (1.0 - vad_speech_frac) * cov_norm
            scored.append({**c, "score": score, "top_event_idx": top_event_idx,
                            "top_event_label": id2label[top_event_idx], "top_event_prob": top_event_prob,
                            "vad_speech_frac": vad_speech_frac, "speech_prob": speech_prob, "energy_cov": cov})
        except Exception as e:
            print(f"[ego4d-expand] shard {args.shard_idx}: candidate {i} FAILED "
                  f"({c['path']}@{c['start_sec']:.1f}s): {e!r}", flush=True)
            continue

        if (i + 1) % 500 == 0 or i == len(my_candidates) - 1:
            with open(out_path, "w") as f:
                json.dump(scored, f)
            elapsed = time.time() - t_start
            print(f"[ego4d-expand] shard {args.shard_idx}: {len(scored)}/{len(my_candidates)} scored, "
                  f"elapsed={elapsed/60:.1f}min", flush=True)

    with open(out_path, "w") as f:
        json.dump(scored, f)
    print(f"[ego4d-expand] shard {args.shard_idx} DONE: {len(scored)} scored -> {out_path}", flush=True)


if __name__ == "__main__":
    main()
